Use String as default type (#596)
When using the criteria builder, adding a parameter with a non-primitive data type to 'Where' and clicking 'Apply selection', the following exception occurs.
Examples: Alter, Sterbedatum, Composer, Postfach in GECCO_Personendaten
It seems that most non-primitive type are passed as strings, therefore I would use that as a default.

```
JSON parse error: Could not resolve type id 'TEMPORAL_AMOUNT' as a subtype of `org.ehrbase.openehr.sdk.aql.dto.operand.Operand`: known type ids = [Boolean, Double, IdentifiedPath, Long, Null, QueryParameter, SingleRowFunction, String, Temporal, TerminologyFunction] (for POJO property 'value')

org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Could not resolve type id 'TEMPORAL_AMOUNT' as a subtype of `org.ehrbase.openehr.sdk.aql.dto.operand.Operand`: known type ids = [Boolean, Double, IdentifiedPath, Long, Null, QueryParameter, SingleRowFunction, String, Temporal, TerminologyFunction] (for POJO property 'value')
```

Co-authored-by: Andreas Kling <andreas.kling@bioquant.uni-heidelberg.de>